Allow customize TextField support text color
SwitchDreams/switch-ui pull request #140
Opened 2024-10-18 12:04 UTC by griseduardo

### Descrição
Permite customizar a cor do `supportText` do `TextField`. Para isso foi criada a props `supportTextColor`.
Esse PR corresponde a issue: https://github.com/SwitchDreams/switch-ui/issues/136

### Observações

Como as cores de texto via tailwind começam sempre com `text-`, deixei a props `supportTextColor` apenas com a cor em si

### Checklist

- [ ] Fiz o link com a task do clickup.
- [x] Fiz minha própria revisão do código.
- [x] Realizei os testes que compravam que a funcionalidade está funcionando corretamente.

2024-10-18 18:28 UTC, PedroAugustoRamalhoDuarte reviewed
@griseduardo Tu poderia me informar uma coisa? Achei muito massa tu achar nosso repo, mas como que tu achou? Atualmente a gente só usa internamente e não divulgamos tanto

2024-10-18 18:29 UTC, PedroAugustoRamalhoDuarte requested changes
O que eu pensei aqui talvez seja só passar um `supportTextClassName` de parametro e a gente conseguir customizar assim.
- Lembra de usar o tailwind merge para mergear as classes padrões e o novo `supportTextClassName`
- Depois por gentileza coloca na documentação com o storybook essa nova props para o componente de input

2024-10-18 21:44 UTC, griseduardo commented on src/internal/SupportOrErrorMessage.tsx
> +}: ErrorMsgProps) => {
Verdade, segui suas sugestões abaixo para resolver esse problema

2024-10-18 21:50 UTC, griseduardo commented
> @griseduardo Tu poderia me informar uma coisa? Achei muito massa tu achar nosso repo, mas como que tu achou? Atualmente a gente só usa internamente e não divulgamos tanto

Eu estou participando da Hacktoberfest, que é um evento onde o objetivo é contribuir em 4 PRs em projetos open source no mês de outubro. O requisito é o repositório ter o topic `hacktoberfest`.
Então fiz um filtro dos repositórios por dois tópicos: `hacktoberfest` e `react`. Acabei encontrando esse repositório e me interessei em contribuir. Vi que usa tailwind, que tive pouco contato no trabalho, tive mais contato com projetos usando styled-components e css modules, então achei uma boa oportunidade para ter mais contato com tailwind.

@PedroAugustoRamalhoDuarte realizei as alterações sugeridas

2024-10-20 13:43 UTC, PedroAugustoRamalhoDuarte approved these changes
@griseduardo Muito obrigado pela PR!!

2024-10-20 13:45 UTC, merged